services:

  spring-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - default
      - secure-backend
    # depends_on:
    #   spring-database:
    #     condition: service_healthy
    #   spring-queue:
    #     condition: service_healthy

  spring-database:
    image: postgres:18.3
    restart: unless-stopped
    networks:
      - default
      - secure-backend
    volumes:
      - postgres-data:/var/lib/postgresql
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
    env_file:
      - compose.env
    ports:
      - target: 5432
        published: 5432
        host_ip: "127.0.0.1"
        protocol: tcp
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s

  spring-queue:
    image: rabbitmq:4.3.2-management
    restart: unless-stopped
    networks:
      - default
      - secure-backend
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "5672:5672"   # Puerto AMQP (comunicación entre aplicaciones y RabbitMQ)
      - "15672:15672" # Puerto de management UI (consola web: http://localhost:15672)
    # healthcheck:
    #   test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s

networks:
  default: {} # red normal con acceso a internet
  secure-backend:
    internal: true # red aislada solo para comunicación interna

volumes:
  postgres-data:

# ¿Qué hace internal: true? Aísla la red completamente del exterior. 
# Los contenedores dentro de ella solo pueden hablarse entre sí, sin acceso a internet.
# ¿Por qué es un problema? Tu spring-api necesita descargar dependencias de Maven y 
# conectarse a internet durante el build. 
# Con internal: true, eso está bloqueado.